# Generated by Django 5.2 on 2026-03-23 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ASP', 'Aspirante'), ('RYC', 'Registro y Control'), ('MEI', 'Mercadeo Institucional'), ('CPG', 'Coordinador de Programa')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=100)),
                ('applicant_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PREI', 'Pre-inscripción'), ('FORM', 'Diligenciando formulario'), ('FINA', 'Finalizo inscripción formulario completo'), ('APRO', 'Aprobada la inscripción'), ('CORR', 'Corregir la inscripción'), ('ADMI', 'Admitido'), ('REJE', 'Rechazado')], default='PREI', max_length=4)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_user', models.EmailField(max_length=254, verbose_name='Email de usuario a validar')),
                ('email_aspiring', models.EmailField(max_length=254, verbose_name='Email del aspirante')),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant_registration.application')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('place_birth', models.CharField(max_length=100, verbose_name='Lugar de nacimiento')),
                ('home_address', models.CharField(max_length=150, verbose_name='Direccion residencia')),
                ('stratum', models.PositiveSmallIntegerField(verbose_name='Estrato')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('document', models.FileField(upload_to='documents/')),
                ('diploma', models.FileField(upload_to='diplomas/')),
                ('question_one', models.TextField()),
                ('question_two', models.CharField(max_length=100, verbose_name='Pregunta dos')),
                ('question_three', models.CharField(max_length=100, verbose_name='Pregunta tres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicant_registration.application')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sesion_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de sesion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado sesion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
